# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a456a7ce7f1fb93e5bd7aafc443127f125f8b54762addc345e07ddf1912ffd45428ecafe0b23572b9a298e2d25302ea8a2c702616029195cc3e37ea22bdfde1b

test:
  secret_key_base: 0431754a6f53bdaf439a6dd709f5c1ca521bf55c2998056721ac1529e9fd606b6d9df2a34d513f5ab27921d0aff586d4d5517966fa89ed5986e08773f6427231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
